### ISSUE TITLE
احتساب الكسور

### ISSUE THREAD

**Issue by jalaany** [ASammour/Tafqeet#2]
السلام عليكم ورحمة الله وبركاته 

مرحبا اخي الكريم اشكرك على الكود الرائع بصراحة 

استاذي هل يمكن تحديث الكود ليعمل ويدعم الكسور بعد الفاصله 

مثلا 
53.525
فقط ثلاثة وخمسون ديناراً كويتياً وخمسمائة وخمسة وعشرون فلساً لا غير

مثال السكربت في هذا الموقع 
http://tafqit.com/

او مثال هذا السكربت 
`var th = ['', 'ألف', 'مليون', 'مليار', 'تريليون'];
var dg = ['صفر', 'واحد', 'اثنين', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة'];
var tn = ['عشرة', 'أحد عشر', 'اثني عشر', 'ثلاثة عشر', 'أربعة عشر', 'خمسة عشر', 'ستة عشر', 'سبعة عشر', 'ثمانية عشر', 'تسعة عشر'];
var tw = ['عشرون', 'ثلاثون', 'الأربعين', 'خمسين', 'ستين', 'السبعين', 'ثمانين', 'تسعين'];

function toWords(s) {
s = s.toString();
s = s.replace( /[\, ] /g, '');
if (s != parseFloat(s)) return 'لیس عدد';
var x = s.indexOf('.');
if (x == -1) x = s.length;
if (x > 15) return 'كبير جدا';
var n = s.split('');
var str = '';
var sk = 0;
for (var i = 0; i < x; i++) {
if ((x - i) % 3 == 2) {
if (n[i] == '1') {
str += ' ' + tn[Number(n[i + 1])];
i++;
sk = 1;
} else if (n[i] != 0) {

str +=  ' ' + tw[n[i] - 2] ;

}
} else if (n[i] != 0) {
str +=  ' ' + dg[n[i]] ;
if ((x - i) % 3 == 0) 
str += ' مائة و';
sk = 2;
}
if ((x - i) % 3 == 1) {
if (sk) str += ' ' + th[(x - i - 1) / 3] ;
sk = 0;
}
}
if (x != s.length) {
var y = s.length;
str += 'و ';
for (var i = x + 1; i < y; i++) 
str +=  ' ' + dg[n[i]] ;
}
return str.replace(/\s+/g, ' ');
}

console.log("23 : "+ toWords(23));
console.log("120: "+ toWords(120));

    $(function () {
        $("#Text1").keyup(function () {
            var val = $(this).val();

            var rex = /^[0-9]+\.[0-9]+$/;
            var isdecimal = rex.test(val);

            var result = "";
            if (isdecimal) {
                result = toWords(val.split('.')[0]) + " ريال و" + toWords(val.split('.')[1]) + " بيسة";
            } else {
                result = toWords(val.split('.')[0]) + " ريال و" ;
            }

            $("#result").html("<b>" + result + "</b>");
        })
    })
    </script>`

**Comment by ASammour** [comment]
وعليكم السلام ورحمة الله وبركاته. وشكرًا لك أخي على كلامك الطيب.

أودّ جعل هذا الكود للاستخدام العام؛ أي أن يتم استخدامه من قبل أي مستخدم. ثم يُمكن له أن يقوم بتخصيصه ليُناسب احتياجه. سواء كان يريده في النقود، أو في التاريخ، وغيرها من الأمور. التعديل الذي تطلبه مشكورًا في احتساب الكسور ممكن، ولكن المشكلة أنه يلزم وجود تمييز بعد  قراءة الكسر مثل "فلسًا"، أو "سنتًا"، "هللةً"...إلخ. وهذه مشكلة تجعل المستخدمين يتقيدون بوجوب وجود تمييز للكسر.

إذا أردت يُمكن تعديل الكود ليصبح كالآتي:

**123.34** 
تُصبح 
**مائة وثلاثة وعشرون فاصلة أربعة وثلاثين**
أو
**مائة وثلاثة وعشرون فارزة أربعة وثلاثين**

هل هذا مناسب؟. أعتقد أن هذا الحل مناسب لمنع التقيّد بوجود تمييز للكسر.

تحياتي. ومرحبًا بأي استفسار آخر.

**Comment by jalaany** [comment]
ربي يسعدك استاذي الكريم

ياريت لوتكرمت تعدل على الكود ليقبل الكسور الثلاثة
مثل
125.245
ليصبح
مائة وخمسة وعشرون فاصلة مائتان وخمسة واربعون

ليستفيد منها الجميع وفي ميزان حسناتك
تقبل تحياتي

**Comment by ASammour** [comment]
**تم** بناءً على طلبك. لأي أمر آخر أرجو ألا تتردد في سؤالي.

أطيب التحيات.

**Comment by jalaany** [comment]
حياك الله استاذي
جزاك الله خيرا على ما قدمت فعلا استفدت منه
وشامل للكل الفئات وسهل التعامل معه
